region                                          = "us-west-1b"
project_name                                    = "devopsdev"
vpc_cidr_block                                  = "10.0.0.0/16"
instance_tenancy                                = "default"
public_sub_cidr                                 = ["10.0.1.0/24", "10.0.2.0/24"]
private_sub_cidr                                = ["10.0.3.0/24", "10.0.4.0/24"]
aws_internet_gateway                            = "IGW"
internet_gateway_route_cidar                    = "0.0.0.0/0"
nat_gateway                                     = "Final-proj-Nat-GW"
nat_gateway_route_cidr                          = "0.0.0.0/0"
instance_type                                   = "t3.micro"
instance_class                                  = "db.t3.micro"
ami                                             = "ami-078a289ddf4b09ae0"
enable_dns_hostnames                            = true
enable_dns_support                              = true
engine_version                                  = "12.14"
engine                                          = "postgreSQL"
allocated_storage                               = 30
storage_type                                    = "gp2"
inbound_ports                                   = 80